# shellcheck shell=bash

if [[ $- != *i* ]]; then
    return
fi

case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

if [[ -r $HOME/.local/share/blesh/ble.sh ]]; then
    source "$HOME/.local/share/blesh/ble.sh" --attach=none
fi

if command -v oh-my-posh > /dev/null 2>&1; then
    eval "$(oh-my-posh init bash --config "$HOME/.config/oh-my-posh/emodipt-extend.omp.json")"
fi

if command -v atuin > /dev/null 2>&1; then
    eval "$(atuin init bash)"
fi

if command -v zoxide > /dev/null 2>&1; then
    eval "$(zoxide init bash)"
fi

if [[ ${BLE_VERSION-} ]]; then
    ble-attach
fi

